#!/usr/bin/perl
use strict;
use warnings;


my %config = ();

sub verifConfig {
    $config{"logfile"} and $config{"clients"} and $config {"port"} and $config{"error"} and $config{"index"} or die "Missing config parameter\n";
}
sub initConfig {
    open(CONFIG, "./comanche.conf") or die ("Error openning config file\n");
    my @param = ();
    while(<CONFIG>){
        if(/set\ */){
            @param = split / /, $_;
            $config{$param[1]} = $param[2];
        }
    }

    verifConfig();

    close(CONFIG);
}

initConfig();